name: masamenu
description: "QR Menü Sistemi - İşletmeler için dijital menü çözümü"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1

  # State Management
  provider: ^6.1.2

  # Routing
  go_router: ^14.0.2

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7

  # UI Components
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.66.2

  # Utilities
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  path: ^1.8.3
  uuid: ^4.3.2

  # File & Image Picking
  image_picker: ^1.0.7
  file_picker: ^8.0.0

  # HTTP & Network
  dio: ^5.4.1
  connectivity_plus: ^5.0.2

  # Local Storage
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9

  # Animation
  lottie: ^3.1.0
  animations: ^2.0.11

  # PDF Generation
  pdf: ^3.10.8

  # Loading & Progress
  flutter_spinkit: ^5.2.0

  # Date & Time
  table_calendar: ^3.0.9

  # Charts & Analytics
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
